# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zW-JjHOHUtxOvEY_aKfFeRUfXHA8CL9V
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark=SparkSession.builder\
.appName("Basics")\
.getOrCreate()

spark.version

data=[
    {"name":"Kusum","age":22},
    {"name":"Arun","age":26},
    {"name":"B","age":2}

]

df=spark.createDataFrame(data)
df.show()

df.printSchema()

df.select("name").show()
df.select("name","age").show()

df.filter(df.age >20).show()
df.filter(df.name=="Bishal").show()

from pyspark.sql.functions import col
df2=df.withColumn("aggg",col("age")+5)
df2.show()



from pyspark.sql.functions import lower
df3=df.withColumn("name_lower",lower(col("name")))
df3.show()

df.drop("age").show()
